### PR TITLE
Initial Commit

### PR DESCRIPTION
**Pull request by fncischen**
@ryanboris initial commit

### CODE REVIEW

**Review by secantsquared — COMMENTED** [review]
Set up correctly, @fncischen  thank you!

**Review by secantsquared — CHANGES_REQUESTED** [review]
Go through the entirety of the CSS and change left/right influenced properties to responsive units. 

Also, the tablet and phone breakpoints do not match the design guides... You may be mid progress working on this and I'm sure you are aware so I will check in the morning.
Cleaning up those breakpoints and giving the transitions fluidity through the use of responsive units should help you out and help you add those nice finishing touches.

**Comment by fncischen** [comment]
Hi @ryanboris! Yep, I was aware that the breakpoints did not match the design guidelines. Had to review flex box & media queries a few more times, but made the final changes - and they should be close to matching.

Best,

**Comment by fncischen** [comment]
closed

**Pull request closed without merging**
